- name: "find out if PostgreSQL is initialized"
  become: yes
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "initialize PostgreSQL"
  become: yes
  command: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "start and enable PostreSQL service"
  become: yes
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
